# Generated by Django 5.2.8 on 2025-11-29 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientlicenseinfo',
            old_name='license_count',
            new_name='total_licenses',
        ),
        migrations.AddField(
            model_name='clientlicenseinfo',
            name='used_licenses',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
